schema_version: 1.2.0
id: CVE-2021-28363
aliases:
- GHSA-5phf-pp7p-vc2r
modified: 2021-12-08T19:58Z
published: 2021-03-15T18:15Z
details: The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate
  validation in some cases involving HTTPS to HTTPS proxies. The initial connection
  to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify
  the hostname of the certificate. This means certificates for different servers that
  still validate properly with the default urllib3 SSLContext will be silently accepted.
severity:
- type: CVSS_V3
  score: 6.5
- type: CVSS_V2
  score: 6.4
affected:
- package:
    name: urllib3
    cpe: cpe:2.3:a:python:urllib3
- ranges:
  - type: GIT
    repo: https://github.com/urllib3/urllib3
    events:
    - introduced: '0'
    - fixed: main
  - type: GIT
    repo: https://github.com/urllib3/urllib3
    events:
    - introduced: '0'
    - fixed: 8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
- database_specific:
    CWE:
    - CWE-295
    CVSS:
      Score: 6.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
references:
- type: ADVISORY
  url: https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4S65ZQVZ2ODGB52IC7VJDBUK4M5INCXL/
- type: WEB
  url: https://security.gentoo.org/glsa/202107-36
- type: WEB
  url: https://pypi.org/project/urllib3/1.26.4/
- type: WEB
  url: https://www.oracle.com/security-alerts/cpuoct2021.html
- type: FIX
  url: https://github.com/urllib3/urllib3/commits/main
- type: FIX
  url: https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
