schema_version: 1.2.0
id: CVE-2016-10149
aliases: []
modified: 2018-01-05T02:30Z
published: 2017-03-24T14:59Z
details: XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows
  remote attackers to read arbitrary files via a crafted SAML XML request or response.
severity:
- type: CVSS_V3
  score: 7.5
- type: CVSS_V2
  score: 5.0
affected:
- package:
    name: debian_linux
    cpe: cpe:2.3:o:debian:debian_linux
- ranges:
  - type: GIT
    repo: https://github.com/rohe/pysaml2
    events:
    - introduced: '0'
    - fixed: 6e09a25d9b4b7aa7a506853210a9a14100b8bc9b
- versions:
  - '8.0'
- database_specific:
    CWE:
    - CWE-611
    CVSS:
      Score: 7.5
      Severity: HIGH
      Code: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
references:
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:0936
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:0938
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:0937
- type: FIX
  url: https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b
- type: WEB
  url: http://www.securityfocus.com/bid/97692
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2017/01/19/5
- type: REPORT
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716
- type: ADVISORY
  url: http://www.debian.org/security/2017/dsa-3759
- type: REPORT
  url: https://github.com/rohe/pysaml2/issues/366
- type: WEB
  url: https://github.com/rohe/pysaml2/pull/379
