schema_version: 1.2.0
id: CVE-2020-5274
aliases:
- GHSA-m884-279h-32v2
modified: 2020-04-01T20:34Z
published: 2020-03-30T20:15Z
details: In Symfony before versions 5.0.5 and 4.4.5, some properties of the Exception
  were not properly escaped when the `ErrorHandler` rendered it stacktrace. In addition,
  the stacktrace were displayed even in a non-debug configuration. The ErrorHandler
  now escape alls properties of the exception, and the stacktrace is only display
  in debug configuration. This issue is patched in symfony/http-foundation versions
  4.4.5 and 5.0.5
severity:
- type: CVSS_V3
  score: 5.4
- type: CVSS_V2
  score: 5.5
affected:
- package:
    name: symfony
    cpe: cpe:2.3:a:sensiolabs:symfony
- ranges:
  - type: GIT
    repo: https://github.com/symfony/symfony
    events:
    - introduced: '0'
    - fixed: cf80224589ac05402d4f72f5ddf80900ec94d5ad
  - type: GIT
    repo: https://github.com/symfony/symfony
    events:
    - introduced: '0'
    - fixed: 629d21b800a15dc649fb0ae9ed7cd9211e7e45db
- database_specific:
    CWE:
    - CWE-209
    CVSS:
      Score: 5.4
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N
references:
- type: FIX
  url: https://github.com/symfony/symfony/commit/cf80224589ac05402d4f72f5ddf80900ec94d5ad
- type: FIX
  url: https://github.com/symfony/symfony/commit/629d21b800a15dc649fb0ae9ed7cd9211e7e45db
- type: ADVISORY
  url: https://github.com/symfony/symfony/security/advisories/GHSA-m884-279h-32v2
