schema_version: 1.2.0
id: CVE-2021-37654
aliases:
- GHSA-2r8p-fg3c-wcj4
modified: 2021-08-18T14:30Z
published: 2021-08-12T21:15Z
details: TensorFlow is an end-to-end open source platform for machine learning. In
  affected versions an attacker can trigger a crash via a `CHECK`-fail in debug builds
  of TensorFlow using `tf.raw_ops.ResourceGather` or a read from outside the bounds
  of heap allocated data in the same API in a release build. The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L660-L668)
  does not check that the `batch_dims` value that the user supplies is less than the
  rank of the input tensor. Since the implementation uses several for loops over the
  dimensions of `tensor`, this results in reading data from outside the bounds of
  heap allocated buffer backing the tensor. We have patched the issue in GitHub commit
  bc9c546ce7015c57c2f15c168b3d9201de679a1d. The fix will be included in TensorFlow
  2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3,
  and TensorFlow 2.3.4, as these are also affected and still in supported range.
severity:
- type: CVSS_V3
  score: 7.1
- type: CVSS_V2
  score: 3.6
affected:
- package:
    name: tensorflow
    cpe: cpe:2.3:a:google:tensorflow
- ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: '0'
    - fixed: bc9c546ce7015c57c2f15c168b3d9201de679a1d
- versions:
  - 2.5.0
  - 2.6.0
- database_specific:
    CWE:
    - CWE-125
    CVSS:
      Score: 7.1
      Severity: HIGH
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/bc9c546ce7015c57c2f15c168b3d9201de679a1d
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2r8p-fg3c-wcj4
