schema_version: 1.2.0
id: CVE-2021-29555
aliases:
- GHSA-r35g-4525-29fq
modified: 2021-05-18T19:58Z
published: 2021-05-14T20:15Z
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can cause a denial of service via a FPE runtime error in `tf.raw_ops.FusedBatchNorm`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/828f346274841fa7505f7020e88ca36c22e557ab/tensorflow/core/kernels/fused_batch_norm_op.cc#L295-L297)
  performs a division based on the last dimension of the `x` tensor. Since this is
  controlled by the user, an attacker can trigger a denial of service. The fix will
  be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow
  2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also
  affected and still in supported range.
severity:
- type: CVSS_V3
  score: 5.5
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: tensorflow
    cpe: cpe:2.3:a:google:tensorflow
- ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: '0'
    - fixed: 1a2a87229d1d61e23a39373777c056161eb4084d
- database_specific:
    CWE:
    - CWE-369
    CVSS:
      Score: 5.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
references:
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-r35g-4525-29fq
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/1a2a87229d1d61e23a39373777c056161eb4084d
