schema_version: 1.2.0
id: CVE-2018-7206
aliases: []
modified: 2021-01-13T14:52Z
published: 2018-02-18T03:29Z
details: An issue was discovered in Project Jupyter JupyterHub OAuthenticator 0.6.x
  before 0.6.2 and 0.7.x before 0.7.3. When using JupyterHub with GitLab group whitelisting
  for access control, group membership was not checked correctly, allowing members
  not in the whitelisted groups to create accounts on the Hub. (Users were not allowed
  to access other users' accounts, but could create their own accounts on the Hub
  linked to their GitLab account. GitLab authentication not using gitlab_group_whitelist
  is unaffected. No other Authenticators are affected.)
severity:
- type: CVSS_V3
  score: 8.8
- type: CVSS_V2
  score: 6.5
affected:
- package:
    name: oauthenticator
    cpe: cpe:2.3:a:jupyter:oauthenticator
- ranges:
  - type: GIT
    repo: https://github.com/jupyterhub/oauthenticator
    events:
    - introduced: '0'
    - fixed: 1845c0e4b1bff3462c91c3108c85205acd3c75a2
- versions:
  - 0.7.2
  - 0.6.1
  - 0.7.0
  - 0.7.1
  - 0.6.0
- database_specific:
    CWE:
    - NVD-CWE-noinfo
    CVSS:
      Score: 8.8
      Severity: HIGH
      Code: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/jupyterhub/oauthenticator/commit/1845c0e4b1bff3462c91c3108c85205acd3c75a2
- type: WEB
  url: https://blog.jupyter.org/security-fix-for-jupyterhub-gitlab-oauthenticator-7b14571d1f76
- type: WEB
  url: https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16
